### ISSUE TITLE
Need to migrate config to yaml by Sept

### ISSUE THREAD

**Issue by AlexanderPico** [cytoscape/cytoscape-manual#68]
https://blog.readthedocs.com/migrate-configuration-v2/

**Comment by bdemchak** [comment]
I just morphed the py4cytoscape .readthedocs.yaml file ... it existed, specified version:2, but contained a deprecated python.version command. Here's the file that readthedocs likes for py4cytoscape 1.8, which is about to be released:
```

# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: doc/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
   install:
   - requirements: doc/requirements.txt

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
```

**Comment by khanspers** [comment]
I added the yaml config file and it seems to have worked (successful build in ReadTheDocs interface). Below is what's in the file. I kept the ubuntu and python versions the same as what was suggested in the blogpost, which is different than what Barry used:
```

# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# We recommend specifying your dependencies to enable reproducible builds:
# https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html
python:
  install:
  - requirements: docs/requirements.txt
 ```
